services:

  backend:
    build: ./backend
    container_name: grocify-backend
    ports:
      - "8080:8080"
      - "9990:9990"
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: grocify-db
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: grocify
      POSTGRES_USER: grocify_user
      POSTGRES_PASSWORD: grocify_pass


  frontend:
    build: ./frontend
    container_name: grocify-frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend